# Generated by Django 6.0.7 on 2026-07-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
