# Generated by Django 6.0.7 on 2026-07-27 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="last_message",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 27, 6, 16, 49, 63027, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
