# Generated by Django 5.2.10 on 2026-07-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_snapuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
    ]
