# Generated by Django 6.0.7 on 2026-07-27 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_chat_last_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="streak_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 27, 7, 24, 2, 430877, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="last_message",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 27, 7, 24, 2, 431052, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
