# Generated by Django 6.0.7 on 2026-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="snaps"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
