# Generated by Django 5.2.10 on 2026-07-27 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chat_streak_updated_at_alter_chat_last_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="last_message",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chat",
            name="streak_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
